### ISSUE TITLE
Method 'xxxx' not found in Qcloud\Cos\Client

### ISSUE THREAD

**Issue by wolfbolin** [tencentyun/cos-php-sdk-v5#101]
虽然在运行的时候不影响使用，但是这个波浪线就很难受啊

![TIM截图20190329010422](https://user-images.githubusercontent.com/25290907/55177806-0e2dd980-51bf-11e9-8372-ddce63c3447a.png)

**Comment by lewzylu** [comment]
这个sdk是基于描述语言实现的，所以ide可能会无法识别method
