### ISSUE TITLE
只有上传下载资源，没有Api里的删除和批量删除吗

### ISSUE THREAD

**Issue by runmanz** [tencentyun/cos-php-sdk-v5#107]
眼没花的话应该是没找到delete object和delete multiple object这两个接口的

**Comment by lewzylu** [comment]
PHP SDK provides two interfaces for deleteObject and deleteObjects to delete objects, 
For reference https://cloud.tencent.com/document/product/436/34282#.E5.88.A0.E9.99.A4.E5.A4.9A.E4.B8.AA.E5.AF.B9.E8.B1.A1.
