### ISSUE TITLE
$this->signature 值是否未进行初始化？

### ISSUE THREAD

**Issue by koowave** [tencentyun/cos-php-sdk-v5#108]
版本：v1.3.4 
文件：/src/Qcloud/Cos/UploadBodyMiddleware.php
运行报错：Call to a member function signRequest() on null 
看了下代码，好像是这个地方：
public function __invoke(RequestInterface $request, array $options) {
        $fn = $this->nextHandler;
        return $fn($this->signature->signRequest($request), $options);
    }
是不是$this->signature没有进行初始化，v1.3.3是正常得，v1.3.4会报错。

**Comment by lewzylu** [comment]
很抱歉，这边用了最新的master分支release了1.3.4版本，现已修复，应该使用1.3分支进行release，现已修复，update即可
