### ISSUE TITLE
PHP对象存储cos-sdk-v5依赖的guzzle升级造成不兼容

### ISSUE THREAD

**Issue by a1xiaoyaozi** [tencentyun/cos-php-sdk-v5#111]
PHP版本 7.1
上传COS文件代码
```
            $result = $this->cosClient->Upload(
                $bucket = $bucketName,
                $key = $KeyForUpload,
                $body = $file
            );
```
将qcloud/cos-sdk-v5版本从1.3.2升级成为1.3.4，由于该SDK依赖的guzzle包升级成为guzzlehttp导致返回的 $result变量的值发生了改变，$result["Location"] 取值不存在，无法获取COS文件的URL地址，希望作者在升级版本时标注一下版本改动情况

**Comment by lewzylu** [comment]
好的，guzzle6的版本我们这边还没有release，会进行进一步的修改。感谢您的建议。
