### ISSUE TITLE
上传图片但header显示的是application/octet-stream

### ISSUE THREAD

**Issue by xiebruce** [tencentyun/cos-php-sdk-v5#113]
如图，上传图片，假如是jpg的，content-type应该是`image/jpeg`，png图片应该是`image/png`，gif应该是`image/gif`，而不是全都是`application/octet-stream`：
![image](https://user-images.githubusercontent.com/13575500/64590398-0616ce80-d3da-11e9-853c-d2c8707019b6.png)

上传代码如下：
```php
$cosClient = new Client([
    'region' => $this->region,
    'credentials' => [
        'secretId' => $this->secretId,
        'secretKey' => $this->secretKey,
    ],
]);

$fp = fopen($uploadFilePath, 'rb');
/** @var Result $retObj */
$retObj = $cosClient->Upload($this->bucket, $key, $fp);
is_resource($fp) && fclose($fp);
```

**Comment by lewzylu** [comment]
If you upload without the `content-type` header, you will carry the `application/octet-stream` by default, which will be automatically converted to the corresponding `content-type` when you download it.

**Comment by xiebruce** [comment]
这还得自己指定啊，我看别的云都是默认文件本身的content-type的，因为你用`application/octet-stream`的话，会导致在网页上查看不了图片，会变成下载，有时候想看看图片就不方便。我用aws s3兼容接口上传就正常，文件本来的mime是什么上传后就是什么，都不用自己指定，所以你们这个这么搞有点不太科学

**Comment by lewzylu** [comment]
感谢您的建议，这个地方的产品策略我们先内部对齐一下

**Comment by xiebruce** [comment]
好的，谢谢！

**Comment by lewzylu** [comment]
这应该是guzzle6版本phpsdk的一个bug，默认会携带`application/octet-stream`的头部去上传。现在已经修复，如果不带cotent-type上传的文件，浏览器下载时会默认预览

**Comment by xiebruce** [comment]
修复了后面再发版本是吗？

**Comment by lewzylu** [comment]
可以先用一下dev的版本，这边ut覆盖率上去后就会release2.0.0

**Comment by xiebruce** [comment]
好的

**Comment by nagatoyk** [comment]
临时决解方案是修改BodyLocation.php的第48行
`$request = $request->withHeader('Content-Type', 'application/octet-stream');`
修改为如下代码即可
`$request = $request->withHeader('Content-Type', $command->hasParam('contenttype')?$command['contenttype']:'application/octet-stream');`

**Comment by xiebruce** [comment]
@nagatoyk 官方已经解决了
