### ISSUE TITLE
guzzle/guzzle升级成guzzlehttp/guzzle后有bug

### ISSUE THREAD

**Issue by xiebruce** [tencentyun/cos-php-sdk-v5#114]
之前提过一个issue，因为[guzzle/guzzle](https://packagist.org/packages/guzzle/guzzle)已经弃用，建议换成新版本：[guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle)，等了好久，终于换了，但也只是换了包，调用方法却没换，导致报错：
![image](https://user-images.githubusercontent.com/13575500/64597821-213d0a80-d3e9-11e9-9612-655fccbae4d5.png)

**Comment by lewzylu** [comment]
Have you updated the vendor package yet,UT is now available through most of the cases. The guzzlehttp version is expected to be released during the Mid-Autumn Festival.

**Comment by lewzylu** [comment]
Have you updated the vendor package yet.
UT is now available through most of the cases. The guzzlehttp version is expected to be released during the Mid-Autumn Festival.

**Comment by xiebruce** [comment]
我就是更新了包才出现这个问题的，更新的是最新的

**Comment by lewzylu** [comment]
如果运行sample/目录下的demo程序会有问题吗。

**Comment by xiebruce** [comment]
直接执行没问题的，我直接调用我的方法也没问题，这个其实是要看设置的报错等级的，因为它并不是错误，它只是警告，就是你们这个sdk现在是可以正常把文件上传到COS的，只不过写的不太兼容Guzzle/http，所以它会有警告，这个肯定要把它改成没有警告比较好。

现在上传成功返回结果是这种格式：
```
GuzzleHttp\Command\Result Object
(
    [ETag] => "8fd59a855e5b1ec15ea9f8ab41b2fc3a"
    [RequestId] => NWQ3ODg1Y2VfMWRhYTk0MGFfMTA0OF8xN2I3YWM0
)
```
跟更新之前不一样，更新之前是有url返回的，虽然不返回也可以自己根据参数拼出来。

**Comment by lewzylu** [comment]
Location这个字段我们这边加一下就可以了；
warning这个我们这边还要研究一下，测试环境下是没有复现的。
可以提供一下php和guzzlehttp版本吗

**Comment by xiebruce** [comment]
用这个开一下报错等级：
```
error_reporting(E_ALL ^E_NOTICE);
```

php版本：
```
PHP 7.3.0 (cli) (built: Jan  3 2019 10:08:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
```

guzzlehttp的版本就是目前最新版本：6.3.3

我要说一下哦，我这边用client执行方式没捕捉到错误，我是用网页调用才显示这个错误的。

**Comment by lewzylu** [comment]
1.Location参数已经加上

**Comment by lewzylu** [comment]
2.这个warning应该也已经修复，可以试一下看

**Comment by xiebruce** [comment]
两个问题仍然存在，难道是我没更新到？我是先`composer remove qcloud/cos-sdk-v5`，再`composer require qcloud/cos-sdk-v5:dev-master`的，github的更新是实时同步到packagist的吧？

**Comment by lewzylu** [comment]
composer不会自动同步的，我刚才update了。

**Comment by xiebruce** [comment]
好的，你可以设置自动同步勾子的，这样不用自己更新，只要github更新了就会自动推到packagist中，我这篇文章有写怎么设置：[https://www.xiebruce.top/1103.html#GithubComposer](https://www.xiebruce.top/1103.html#GithubComposer)

**Comment by xiebruce** [comment]
还是不行，估计没更新到，有哪个文件让你一看就知道有没有更新的？我可以截个图你看看我是不是没更新到。

**Comment by lewzylu** [comment]
好的，我这边学习一下。
https://github.com/tencentyun/cos-php-sdk-v5/blob/master/src/Qcloud/Cos/Client.php#L118 我这边更新这一行

**Comment by xiebruce** [comment]
果然是没更新到，我再更新也不行：
![image](https://user-images.githubusercontent.com/13575500/65213144-8d99c700-dad7-11e9-8fbd-3d2461d4f628.png)

这样确实是下载最新开发版本呀，也许有缓存吧，要不你再在packagist那边点一下update试试：
```
composer require qcloud/cos-sdk-v5:dev-master
```

**Comment by lewzylu** [comment]
packgist上我看已经更新了，本地的话我记得composer update就可以了的

**Comment by xiebruce** [comment]
试了好几次，remove掉都不行，最后我直接删掉composer.json中的qcloud再更新，然后再次执行：
```
composer require qcloud/cos-sdk-v5:dev-master
```
这次终于安装到新代码了，已经验证，两个问题都已经解决，现在没有问题了，就等你们的UT覆盖率上去了没啥问题就可以发版本了。

**Comment by lewzylu** [comment]
Good，thank you for advice
