### ISSUE TITLE
1.3.4版本更新后 上传图片报Undefined variable: bodyParameter，1.3.3正常

### ISSUE THREAD

**Issue by zoulongbo** [tencentyun/cos-php-sdk-v5#115]
Undefined variable: bodyParameter
Undefined variable: bodyParameter
Undefined variable: bodyParameter

**Comment by lewzylu** [comment]
很抱歉，之前1.3.4版本发布出现问题，发布了guzzlehttp的版本，现已修复，麻烦重新composer update一下。
