### ISSUE TITLE
为什么不能自定义api的域名呢?

### ISSUE THREAD

**Issue by static7** [tencentyun/cos-php-sdk-v5#132]
JavaScript 都能自定义域名
看PHP的源码 也没有自定义域名

**Comment by lewzylu** [comment]
Well, we will support it in the next iteration

**Comment by static7** [comment]
> Well, we will support it in the next iteration

还有 一个小小的问题

![image](https://user-images.githubusercontent.com/11241063/70115890-0ef70380-169c-11ea-8e93-3b311c7f146d.png)
这个配置`endpoint`重复了
