### ISSUE TITLE
deleteObject在哪 凭空就能出来吗

### ISSUE THREAD

**Issue by admiao** [tencentyun/cos-php-sdk-v5#144]
composer 的包 你确定能使用deleteObject？你确定如官方文档一样使用 deleteObject ？你是用肛门来想问题吗和写代码吗？

**Comment by sy-records** [comment]
口吐芬芳...提问注意下态度
当然有deleteObject方法，我项目中都正常使用
https://github.com/tencentyun/cos-php-sdk-v5/blob/master/src/Qcloud/Cos/Service.php#L499

**Comment by admiao** [comment]
> 口吐芬芳...提问注意下态度
> 当然有deleteObject方法，我项目中都正常使用
> https://github.com/tencentyun/cos-php-sdk-v5/blob/master/src/Qcloud/Cos/Service.php#L499

![image](https://user-images.githubusercontent.com/24733229/76863754-f6050d80-689a-11ea-9a23-1f522c7d9fd1.png)
按官方示例操作，我是那样觉得 ，你们cos组的代码 。。。

**Comment by sy-records** [comment]
首先我不是官方的，只是个contributor，看到了顺便回你下。
你截图的没看出来什么问题，是编辑器代码提示的问题？deleteObject下的波浪线？
存不存在是执行一下代码就知道，报错就发相关信息

**Comment by admiao** [comment]
> 首先我不是官方的，只是个contributor，看到了顺便回你下。
> 你截图的没看出来什么问题，是编辑器代码提示的问题？deleteObject下的波浪线？
> 存不存在是执行一下代码就知道，报错就发相关信息
感谢 ， 已经解决  ,  系代码问题  。

**Comment by admiao** [comment]
另外 代码封装得不是作秀就系作死 ， 生命有限  ，  难为程序员就是 喷之

**Comment by yoyo837** [comment]
在这看到你的如此的发言表现，也不奇怪你为什么在其他地方一来就一副别人欠你几百万的样子了！

开源项目遇到文档手册功能有时候不完善没有谁是故意的，第一时间想到的不是一起去完善改进，却漫天喷！

不知道你从小到底受到的是什么样的教育，你也就只剩这点到处喷的能力勉强苟活于世了，我要是你我一头撞墙去死，你不适合干这行赶紧想想别的出路吧！

**Comment by zhangbowy** [comment]
> 在这看到你的如此的发言表现，也不奇怪你为什么在其他repo一来就一副别人欠你几百万的样子了！
> 
> 开源项目遇到文档手册功能有时候不完善没有谁是故意的，没人强迫你使用，第一时间想到的不是一起去完善改进，却漫天喷！
> 
> 不知道你从小到底受到的是什么样的教育，你也就只剩这点到处喷的能力勉强苟活于世了，我要是你我一头撞墙去死，你不适合干这行赶紧想想别的出路吧！
666
