### ISSUE TITLE
Fatal error: Cannot redeclare class Extract_Phar in ../include/txsdk/cos-sdk-v5.phar on line 103

### ISSUE THREAD

**Issue by pkuoliver** [tencentyun/cos-php-sdk-v5#148]
Extract_Phar，不加前缀，这样的类名，也是醉了！！！

Fatal error: Cannot redeclare class Extract_Phar in ../include/txsdk/cos-sdk-v5.phar on line 103

**Comment by sy-records** [comment]
这是phar生成的类名...
直接用composer加载不是更方便...

**Comment by pkuoliver** [comment]
项目里面有多个不同的phar，并不是这个cos的phar重复加载

**Comment by sy-records** [comment]
Extract_Phar这是phar扩展自动生成的，可以看https://github.com/php/php-src/blob/master/ext/phar/stub.h#L21-L30
你加载多个phar包肯定会类名冲突，异常抛出在cos，是因为你后加载cos了... 

可以自己手动phar包打个试试
![image](https://user-images.githubusercontent.com/33931153/80068536-5a8a4b00-8572-11ea-88e6-e2c8af50813d.png)

推荐使用composer加载
