### ISSUE TITLE
建议支持 PostObject

### ISSUE THREAD

**Issue by freyo** [tencentyun/cos-php-sdk-v5#159]
现在 Services 里没有看到这个方法。

**Comment by lewzylu** [comment]
有什么场景会需要用到这个接口，可以使用 upload/putobject 替代吗

**Comment by freyo** [comment]
PostObject 签名不一样，见 https://cloud.tencent.com/document/product/436/14690

**Comment by tonyzheng121** [comment]
为什么关了？是有现成的方法了吗？
