### ISSUE TITLE
最新 Laravel 8 版本，composer require 安装不了

### ISSUE THREAD

**Issue by humengcn** [tencentyun/cos-php-sdk-v5#162]
提示 guzzlehttp/guzzle 版本必须是 7.0.1，麻烦更新一下 composer.json 文件

**Comment by lewzylu** [comment]
升级guzzle版本可能会导致部分依赖不兼容，需要后端先测试

**Comment by shijunti19** [comment]
@lewzylu 什么时候好啊，我需要这个官方包

**Comment by lewzylu** [comment]
这周我处理下，看这个库guzzle-services看已经支持guzzle7了

**Comment by shijunti19** [comment]
@lewzylu 好的谢谢，客户需要用腾讯os，然后我们又跟着laravel实时更新的，没办法！不然换到其他商家太麻烦了

**Comment by lewzylu** [comment]
@shijunti19 @humengcn 已经支持了在guzzle7分支，因为大部分服务器还是用的php5，这里暂时应该不会合到；可以试一下，ut应该都是ok，需要php>=7.3

**Comment by shijunti19** [comment]
@lewzylu 这个分支怎么安装的试了好几种都不行
composer require qcloud/cos-sdk-v5:dev-guzzle7

**Comment by lewzylu** [comment]
报的什么错呢，直接拉源码checkout，composer install就可以了

**Comment by sy-records** [comment]
你是不是限制了只能安装stable版本，安装不了的报错贴出来看看，我这里可以安装

**Comment by tony-server** [comment]
composer安装报错，不支持guzzlehttp/guzzle7
` Problem 1
    - qcloud/cos-sdk-v5[dev-master, v2.0.0, ..., v2.1.1] require guzzlehttp/guzzle ~6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires qcloud/cos-sdk-v5 >=2.0 -> satisfiable by qcloud/cos-sdk-v5[v2.0.0, ..., v2.1.1].`

**Comment by shijunti19** [comment]
@tony-server 他们让你拉去源代码本地安装，可以的，就是无法更新的那种，你百度看看就知道了

**Comment by tony-server** [comment]
使用 `composer require overtrue/qcloud-cos-client` 安装了

**Comment by shijunti19** [comment]
@tony-server guzzle7版本不是这个啊，他是分支
