### ISSUE TITLE
当listContents()带有prefix或Delimiter时，会二次urlencode导致签名失败

### ISSUE THREAD

**Issue by pegziq** [tencentyun/cos-php-sdk-v5#163]
`
public function createAuthorization( RequestInterface $request, $expires = '+30 minutes' ) {
        。。。
        foreach ( explode( '&', $request->getUri()->getQuery() ) as $query ) {
            if (!empty($query)) {
                $tmpquery = explode( '=', $query );
                $key = strtolower( urlencode( $tmpquery[0] ) );
                if (count($tmpquery) >= 2) {
                    $value = urlencode( $tmpquery[1] );
                } else {
                    $value = "";
                }
                $urlParamListArray[$key] = $key. '='. $value;
            }
        }
        。。。
    }
`
` $request->getUri()->getQuery() `
和
`urlencode( $tmpquery[1] )`
会两次urlencode，造成签名失败

**Comment by lewzylu** [comment]
感谢您的建议，是v2.1.0版本引入的一个bug，已于v2.1.1版本修复
