### ISSUE TITLE
依赖的guzzlehttp 版本能升级到最新7.2.0 吗 ？

### ISSUE THREAD

**Issue by jhz-code** [tencentyun/cos-php-sdk-v5#165]
依赖的guzzlehttp 版本能升级到最新7.2.0 吗，当前sdk中的guzzlehttp的版本过低 ，与其他应用的sdk冲突了。

**Comment by finecho** [comment]
https://github.com/overtrue/qcloud-cos-client 你值得拥有

**Comment by jhz-code** [comment]
&nbsp;thanks&nbsp;

**Comment by lewzylu** [comment]
guzzle7 branch 已经支持

**Comment by jhz-code** [comment]
thanks
