### ISSUE TITLE
dev-guzzle7版本无法使用

### ISSUE THREAD

**Issue by gvzhang** [tencentyun/cos-php-sdk-v5#208]
guzzle最新版本7.3.0，依赖的`guzzlehttp/psr7": "^1.7 || ^2.0`，已移除Psr7\stream_for语法，使用导致报错：
```text
Error: Call to undefined function GuzzleHttp\Psr7\stream_for()
```

期望指定依赖版本，修复错误。

**Comment by tuuna** [comment]
是guzzle7分支代码吗？我看目前guzzle7分支的composer版本为
```
        "guzzlehttp/guzzle": "^7.0.1",
        "guzzlehttp/guzzle-services": "~1.2"
```

**Comment by gvzhang** [comment]
是的，guzzle7分支代码。`"guzzlehttp/guzzle": "^7.0.1"`会安装最新的guzzle 7.3.0。

**Comment by tuuna** [comment]
目前已经修复了
```
"guzzlehttp/guzzle": "~7.0.1"
```
我看一下7.3.0相关的内容，后续可以升级一下

**Comment by gvzhang** [comment]
可以了，感谢
