### ISSUE TITLE
dev-guzzle无法使用

### ISSUE THREAD

**Issue by wename** [tencentyun/cos-php-sdk-v5#209]
guzzle最新版本7.3.0，依赖的guzzlehttp/psr7": "^1.7 || ^2.0，已移除Psr7\stream_for语法，使用导致报错：

Error: Call to undefined function GuzzleHttp\Psr7\stream_for()
期待指定依赖版本，修复错误。

**Comment by tuuna** [comment]
可以在https://github.com/tencentyun/cos-php-sdk-v5/issues/208中交流一下
