### ISSUE TITLE
需要 Guzzle7   版本啊！不然不兼容微信支付的SDK

### ISSUE THREAD

**Issue by XuanDeMeng** [tencentyun/cos-php-sdk-v5#221]
需要 Guzzle7   版本啊！不然不兼容微信支付的SDK

**Comment by tuuna** [comment]
目前guzzle7分支可以用哈，后续有计划合并兼容

**Comment by XuanDeMeng** [comment]
大哥，牛逼啊，支持composer&nbsp; 安装分支吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月9日(星期四) 晚上9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tencentyun/cos-php-sdk-v5] 需要 Guzzle7   版本啊！不然不兼容微信支付的SDK (#221)





 
目前guzzle7分支可以用哈，后续有计划合并兼容
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuuna** [comment]
目前可以通过`composer require --dev qcloud/cos-sdk-v5:dev-guzzle7`下载哈

**Comment by XuanDeMeng** [comment]
这还有什么说的呢？给你32个赞！折腾一晚上了，早知道早就来这了！
