### ISSUE TITLE
guzzlehttp/guzzle依赖升级

### ISSUE THREAD

**Issue by YepYuYu** [tencentyun/cos-php-sdk-v5#225]
guzzlehttp/guzzle的依赖不打算升升级吗？

搞的和好多包都冲突

**Comment by tuuna** [comment]
目前主分支是6.x，如果你需要使用guzzle7请暂时使用一下guzzle7分支。预计中秋前会发下个版本，自动兼容guzzle6,guzzle7

**Comment by YepYuYu** [comment]
> 目前主分支是6.x，如果你需要使用guzzle7请暂时使用一下guzzle7分支。预计中秋前会发下个版本，自动兼容guzzle6,guzzle7

你好，打算什么时候发布下一个版本呢？

**Comment by tuuna** [comment]
> > 目前主分支是6.x，如果你需要使用guzzle7请暂时使用一下guzzle7分支。预计中秋前会发下个版本，自动兼容guzzle6,guzzle7
> 
> 你好，打算什么时候发布下一个版本呢？

这边需要先等文档审核再发包，不然会出问题。代码已经合进去了。
