### ISSUE TITLE
GuzzleHttp\\Psr7\\Utils' not found

### ISSUE THREAD

**Issue by tangdongjie** [tencentyun/cos-php-sdk-v5#253]
GuzzleHttp\\Psr7\\Utils' not found
upload方法：  $body = Psr7\Utils::streamFor($body);
Psr7找不到

**Comment by sy-records** [comment]
psr7这个组件版本低了吧

**Comment by tangdongjie** [comment]
项目之前有别的composer包用GuzzleHttp 低版本
cos-php-sdk-v5 拉下来并没有覆盖之前的GuzzleHttp
我怎么样可以拉去cos-php-sdk-v5 的时候 提升GuzzleHttp

**Comment by tangdongjie** [comment]
为了不影响项目其他包用guzzlehttp  将cos-php-sdk-v5 换成了2.2.3版本
