### ISSUE TITLE
什么时候能加上 OCR 接口呢？

### ISSUE THREAD

**Issue by charescape** [tencentyun/cos-php-sdk-v5#268]

**Comment by charescape** [comment]
https://cloud.tencent.com/document/product/436/64324

**Comment by nic12347** [comment]
收到，近期安排开发，功能上线后通知您。

**Comment by charescape** [comment]
@nic12347 @tuuna 谢谢，效率很高哦

**Comment by tuuna** [comment]
@charescape 这个版本还没上，预计要下个版本了哈。先close，后续继续跟进

**Comment by nic12347** [comment]
@charescape    https://cloud.tencent.com/document/product/436/64324 OCR识别接口PHP SDK已上线，可以先通过拉取源码并且composer install的方式使用。包需要下周才能上

**Comment by nic12347** [comment]
代码示例：
https://github.com/tencentyun/cos-php-sdk-v5/blob/master/sample/opticalOcrRecognition.php

**Comment by charescape** [comment]
@nic12347 谢谢
