### ISSUE TITLE
包含尖括号<>会失败

### ISSUE THREAD

**Issue by busyphp** [tencentyun/cos-php-sdk-v5#282]
https://github.com/tencentyun/cos-php-sdk-v5/blob/ed2e4f12751a67eecd7df1d0ade42efe1cf09f96/src/Service.php#L3291

StyleBody：imageMogr2/thumbnail/100x100>
会被转为：
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<AddStyle>
  <StyleName>test1</StyleName>
  <StyleBody><![CDATA[imageMogr2/thumbnail/100x100>]]></StyleBody>
</AddStyle>`
接口返回：AddStyle Style StyleName or StyleBody is empty

测试API Exploder请求结构为：
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<AddStyle>
  <StyleName>test1</StyleName>
  <StyleBody>imageMogr2/thumbnail/100x100&lt;</StyleBody>
</AddStyle>`

应该是API不支持 CDATA

**Comment by nic12347** [comment]
感谢反馈，我们验证下
