### ISSUE TITLE
curl_multi_add_handle() expects parameter 2 to be resource, object given

### ISSUE THREAD

**Issue by weizewei** [tencentyun/cos-php-sdk-v5#288]
在hyperf 框架中使用 $cosClient->putObject 简单上传方法时出现次报错。
swoole 版本：4.8.12 

`PHP Warning:  curl_multi_add_handle() expects parameter 2 to be resource, object given in /home/xxxxx/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 155
xxxx
Warning: curl_multi_add_handle() expects parameter 2 to be resource, object given in /home/xxxx/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php on line 155
`

**Comment by tuuna** [comment]
代码贴一下

**Comment by sy-records** [comment]
编译Swoole的时候开启 [SWOOLE_HOOK_NATIVE_CURL](https://wiki.swoole.com/#/runtime?id=swoole_hook_native_curl)
