### ISSUE TITLE
请注释掉无用的打印输出

### ISSUE THREAD

**Issue by tanzhenxing** [tencentyun/cos-php-sdk-v5#29]
@moria @yaozongyou @yishuiliunian @puterjam @konakonall 
调试接口的时候，莫名奇妙的多了下面一行字符，这些是无用的输出，会影响接口的使用，如果会可以去掉，请注释掉
> Guzzle\Common\Collection Object ( [data:protected] => Array ( [min_part_size] => 5242880 [params] => Array ( ) ) ) 

代码位置：qcloud\cos-sdk-v5\src\Qcloud\Cos\Client.php 第103行  print_r($options);

**Comment by lewzylu** [comment]
感谢，已修复
