### ISSUE TITLE
PHP 8.1 无法使用 listObjects()

### ISSUE THREAD

**Issue by big-dream** [tencentyun/cos-php-sdk-v5#290]
代码：
```
$client->listObjects([
  "Bucket" => "cos-1251274180"
  "Delimiter" => "/"
  "EncodingType" => "url"
  "Prefix" => ""
]);
```

错误信息：
```
\vendor\guzzlehttp\guzzle-services\src\ResponseLocation\XmlLocation.php line 147:
strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated
```

PHP 8.0和7.4都没问题，切换到8.1就不行了

**Comment by big-dream** [comment]
PHP 8.0 已经处于仅安全修复阶段了，建议尽早支持 8.1 和 8.2 版本
![image](https://user-images.githubusercontent.com/9215157/208014727-171400fa-af7b-496e-8edd-53346830aa1c.png)

**Comment by RazeSoldier** [comment]
+1

**Comment by cuixiping** [comment]
deprecated 报警可以忽略

```php
error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED);
```

**Comment by big-dream** [comment]
> deprecated 报警可以忽略
> 
> ```
> error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED);
> ```

掩耳盗铃

**Comment by cuixiping** [comment]
> > deprecated 报警可以忽略
> > ```php
> > error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED);
> > ```
> 
> 掩耳盗铃

改源代码也很简单, 报错信息非常明确.

[源文件](https://github.com/guzzle/guzzle-services/blob/4989d902dd4e0411b320e851c46f3c94d652d891/src/ResponseLocation/XmlLocation.php#L147)

```php
if (strstr($sentAs, ':')) {
```

改为

```php
if ($sentAs !== null && strstr($sentAs, ':')) {
```

**Comment by big-dream** [comment]
> > > deprecated 报警可以忽略
> > > ```
> > > error_reporting(E_ALL ^ E_NOTICE ^ E_DEPRECATED);
> > > ```
> > 
> > 
> > 掩耳盗铃
> 
> 改源代码也很简单, 报错信息非常明确.
> 
> [源文件](https://github.com/guzzle/guzzle-services/blob/4989d902dd4e0411b320e851c46f3c94d652d891/src/ResponseLocation/XmlLocation.php#L147)
> 
> ```
> if (strstr($sentAs, ':')) {
> ```
> 
> 改为
> 
> ```
> if ($sentAs !== null && strstr($sentAs, ':')) {
> ```

但这只是临时的解决方法呢

**Comment by cuixiping** [comment]
> >   
> > 改为
> > ```
> > if ($sentAs !== null && strstr($sentAs, ':')) {
> > ```
> 
> 但这只是临时的解决方法呢

哪里临时了? 你改了就一直能用

**Comment by big-dream** [comment]
> > > 改为
> > > ```
> > > if ($sentAs !== null && strstr($sentAs, ':')) {
> > > ```
> > 
> > 
> > 但这只是临时的解决方法呢
> 
> 哪里临时了? 你改了就一直能用

你不用更新 composer 包？每次更新都得去改一次？

**Comment by cuixiping** [comment]
> > > > 改为
> > > > ```
> > > > if ($sentAs !== null && strstr($sentAs, ':')) {
> > > > ```
> > > 
> > > 
> > > 但这只是临时的解决方法呢
> > 
> > 
> > 哪里临时了? 你改了就一直能用
> 
> 你不用更新 composer 包？每次更新都得去改一次？

lock起来, 无事不要随意更新.
