### ISSUE TITLE
代码告警

### ISSUE THREAD

**Issue by crystal9002** [tencentyun/cos-php-sdk-v5#296]
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/9667411/221164215-a0f5cc4d-5ea2-43dc-a2b6-ba3dfb6bef58.png">
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/9667411/221164463-3c80e85c-20b1-4736-8dcb-17a225005169.png">

这里可以改为用strpos去判断

**Comment by sy-records** [comment]
你的php版本和key是什么？
