### ISSUE TITLE
能不能更新下 guzzle这包呢？

### ISSUE THREAD

**Issue by tanzhenxing** [tencentyun/cos-php-sdk-v5#30]
IDE 提示 guzzle/guzzle 过期了，是不是可以更新到新的包guzzlehttp/guzzle
> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by krwu** [comment]
+1

**Comment by tanzhenxing** [comment]
+1? 不好意思，不明白你的意思，@krwu

**Comment by krwu** [comment]
@tanzhenxing +1 意思是支持你的提议，“附议”。

**Comment by Awesomez** [comment]
+1

**Comment by lewzylu** [comment]
抱歉，该sdk的架构都是基于老版本的guzzle，短期内不能更新到最新的guzzle库的。

**Comment by Awesomez** [comment]
加班搞一下嘛

**Comment by tinpont** [comment]
+1 希望能更新一下，跟上时代步伐。

**Comment by xcaptain** [comment]
虽然这代码看着心累但是先凑合着用吧，等有时间了看看能不能造个更好的轮子
