### ISSUE TITLE
Bucket 接口缺少部分支持

### ISSUE THREAD

**Issue by sy-records** [tencentyun/cos-php-sdk-v5#323]
- [ ] [存储桶策略（policy）](https://cloud.tencent.com/document/product/436/35116)
- [ ] [存储桶加密（encryption）](https://cloud.tencent.com/document/product/436/40135)
- [ ] [对象锁定配置（ObjectLock）](https://cloud.tencent.com/document/product/436/55295)
- [ ] [回源（Origin）](https://cloud.tencent.com/document/product/436/82922)

**Comment by tuuna** [comment]
已转迭代
