### ISSUE TITLE
V1.1.2 版本中居然还有print_r()

### ISSUE THREAD

**Issue by daresheep** [tencentyun/cos-php-sdk-v5#37]
具体如下:

文件:qcloud\cos-sdk-v5\src\Qcloud\Cos\Client.php

public function upload($bucket, $key, $body, $options = array()) {
        $body = EntityBody::factory($body);
        $options = Collection::fromConfig(array_change_key_case($options), array(
            'min_part_size' => MultipartUpload::MIN_PART_SIZE,
            'params'        => $options));
        print_r($options);
        if ($body->getSize() < $options['min_part_size']) {
            // Perform a simple PutObject operation
            return $this->putObject(array(
                    'Bucket' => $bucket,
                    'Key'    => $key,
                    'Body'   => $body,
                ) + $options['params']);
        }

第103 行   居然还有一个print_r ....

**Comment by lewzylu** [comment]
v1.1.3已经修复

**Comment by tanzhenxing** [comment]
奇怪，之前我提到过这个问题，
网址：https://github.com/tencentyun/cos-php-sdk-v5/issues/29
怎么同样的问题，又出现了呢？
