### ISSUE TITLE
看你写的文档感觉技术也是不过关哈哈

### ISSUE THREAD

**Issue by mrlixiansheng** [tencentyun/cos-php-sdk-v5#50]
看你写的文档感觉技术也是不过关哈哈

**Comment by mrlixiansheng** [comment]
你们这种写法是错误的

**Comment by qq690712575** [comment]
文档的确不太行啊，我翻来翻去都对不上

**Comment by lewzylu** [comment]
麻烦能给出具体的情景吗，我们这边可以改进

**Comment by qq690712575** [comment]
简单的描述下有哪些方法有什么作用其实这个也差不多了。因为我看那个示例文件基本靠猜

通过我的 Moto X 发送

2018年3月13日 上午9:43于 lewzylu <notifications@github.com>写道：

麻烦能给出具体的情景吗，我们这边可以改进
