### ISSUE TITLE
关于对象存储PHP-SDK，依赖guzzle类库，但是guzzle类库已经更名为guzzlehttp

### ISSUE THREAD

**Issue by itbirds** [tencentyun/cos-php-sdk-v5#54]
我这边使用composer安装腾讯云对象存储COS的PHP SDK，发现SDK依赖guzzle类库，然而现在guzzle类库已经更名，如果以后老的guzzle这个被废弃或不在维护，可能会影响SDK的正常使用，请更新guzzle类库为最新的guzzlehttp.
![qcloud](https://user-images.githubusercontent.com/5441797/38286156-640b53c0-37f6-11e8-91ff-b02ce7d2a962.jpg)

**Comment by tanzhenxing** [comment]
我看到已经更新guzzle 最近版了

**Comment by Vtrois** [comment]
Version | Status | Packagist | Namespace | Repo | Docs | PSR-7 | PHP Version
-- | -- | -- | -- | -- | -- | -- | --
3.x | EOL | guzzle/guzzle | Guzzle | v3 | v3 | No | >= 5.3.3
4.x | EOL | guzzlehttp/guzzle | GuzzleHttp | v4 | N/A | No | >= 5.4
5.x | Maintained | guzzlehttp/guzzle | GuzzleHttp | v5 | v5 | No | >= 5.4
6.x | Latest | guzzlehttp/guzzle | GuzzleHttp | v6 | v6 | Yes | >= 5.5

V3 版本早已经是 EOL 状态了，不会影响使用 @itbirds

**Comment by MikeMaldini** [comment]
那现在怎么说？我是 PHP 7.0  + GUZZLE 6 的  这 SDK 怎么才能正常用

**Comment by Vtrois** [comment]
@MikeMaldini PHP7.x的环境在composer之后依旧可以使用这个SDK啊

**Comment by MikeMaldini** [comment]
![image](https://user-images.githubusercontent.com/29230494/41219480-002bf834-6d91-11e8-8db8-bb7c13b2de5e.png)
![image](https://user-images.githubusercontent.com/29230494/41219550-33b99dbe-6d91-11e8-9ed0-165b638d696a.png)
@Vtrois 
`guzzle` 我也装了，没搞明白 我是不是哪里配置有问题

**Comment by krwu** [comment]
@MikeMaldini 
是 "guzzle/guzzle" 不是 "guzzlehttp/guzzle".

这就是这个 issue 在讨论的问题。

**Comment by MikeMaldini** [comment]
@krwu 所以我必须手动安装老的 `guzzle/guzzle` ？

**Comment by slince** [comment]
建议将第三方依赖从版本库移除；使用composer依赖的方式进行管理维护；

**Comment by krwu** [comment]
@slince 我不是项目团队的，也是这个项目的使用者。现在本来就是通过composer依赖第三方库。问题在于依赖的guzzle/guzzle版本已经严重过时。

**Comment by slince** [comment]
@krwu 哦哦

我看了下源代码，项目依赖了guzzle和symfony的一些组件，但都没有写到composer.json 的require里面 这有点可怕了

**Comment by MikeMaldini** [comment]
@slince 我也发现了这个蛋疼的问题

**Comment by krwu** [comment]
@slince @MikeMaldini 
我也认真看了一遍源码，又用一个空项目做了测试。版本库里的 `Guzzle` 和 `Symfony` 目录实际上是给直接下载版本库的人用的。

用 `composer` 安装项目的人，直接 `require('./vendor/autoload.php')` 的情况下，那两个目录没有任何意义。

`composer require qcloud/cos-sdk-v5` 的时候，会自动安装所需的第三方依赖，并且加载的也是安装的依赖而不是版本库里的 guzzle 和 symfony 相关文件。

测试的步骤：

1. 新建空文件夹
2. 在文件夹下执行 `composer init` 和 `composer require qcloud/cos-sdk-v5`
3. 删除 `vendor/qcloud/cos-sdk-v5/src` 下的 `Guzzle` 和 `Symfony` 目录
4. 创建 `index.php`, 通过 `require('./vendor/autoload.php')` 自动加载依赖
5. 最简单的上传测试

执行的情况，测试通过。

**Comment by Vtrois** [comment]
@yaozongyou 看一下这个问题

**Comment by slince** [comment]
@krwu 

其实既然决定使用composer分发代码，那一切按照composer的要求去做是最合适的；
还是建议你们的同事：

- 移除src 下 guzzle以及symfony目录
- 更新guzzle为guzzlehttp
- .idea 目录移除
- 补充单元测试

腾讯这么大一个厂不能太随心所欲，不讲究开源质量实在是说不过去。

**Comment by yaozongyou** [comment]
@slince @MikeMaldini 感谢两位的建议：
1、src目录下的guzzle和symfony这两个目录，主要是为了方便不使用composer的用户，能把源码下载下来可以直接使用；
2、使用老版本的guzzle而不是guzzlehttp主要是为了兼容php 5.3的版本；
3、.idea目录稍后将删除；
4、关于单元测试方面，现在有功能性方面的测试代码(src/Qcloud/Cos/Tests/Test.php)。

再次感谢两位的建议，谢谢。

**Comment by krwu** [comment]
@yaozongyou 我还是那个建议，发布一个2.x的版本，改用guzzlehttp。毕竟现在安装的时候都已经警告 `guzzle/guzzle is abandoned` 了。保留 1.x 的给 php 5.3 的用户就行了。

**Comment by yaozongyou** [comment]
@krwu 好的，我和@lewzylu先评估下。

**Comment by zuoRambo** [comment]
我是来投票的 烦请移除`guzzle/guzzle` 请腾讯云的朋友看一下 还有多少使用php5.3  社区的发展与技术的革新需要咱们每个人去推动

**Comment by andares** [comment]
都过去几百年了，再下去这个库都要没法用了。。更新一个2.0版本使用新库要不了半天时间吧？

**Comment by jjonline** [comment]
底层http请求还是自己实现比较好~

**Comment by Yveshield** [comment]
又过去几百年了，还是没变化

**Comment by HFLeon** [comment]
又过去几百年了，还是没变化

**Comment by allowing** [comment]
又过去几百年了，还是没变化

**Comment by xiebruce** [comment]
腾讯的人就是这么干事么？这个问题从提出到现在都已经一年零三个月了，还没有解决？技术要严谨，都已经一堆人报这个提示了：
![image](https://user-images.githubusercontent.com/13575500/61040371-03f8b980-a403-11e9-81a0-aa40b3ddd417.png)

我之前还以为我用了老版本，结果找了一遍，本来还以为是小厂，没想到竟然是大厂干的活。。。

都9102年了，老版本的你发个老版本，新版的用新的呀，还有多少人用那老掉牙的。。。

**Comment by lewzylu** [comment]
1、考虑到CVM默认的PHP版本是5.3.3，如果升级guzzle的话，这部分用户接没法兼容了，所以之前的排期优先级较低。

2、目前cos的php sdk是基于guzzle的描述语言实现的，guzzle6不向下兼容，如果升级到guzzlehttp的话相当于要重写，工作量较大。

3、近期我们已经在安排同学来进行相关的重写工作。预计9月初上线

**Comment by xiebruce** [comment]
@lewzylu 好的👍🏻

**Comment by overtrue** [comment]
已经升级了：https://github.com/tencentyun/cos-php-sdk-v5/blob/master/composer.json#L25

**Comment by zuoRambo** [comment]
> 已经升级了：https://github.com/tencentyun/cos-php-sdk-v5/blob/master/composer.json#L25

还是我超哥优秀

**Comment by overtrue** [comment]
@zuoRambo 🤣 不是我改的

**Comment by HFLeon** [comment]
迟到的GZ

**Comment by lewzylu** [comment]
[v2.0](Https://github.com/tencentyun/cos-php-sdk-v5/releases/tag/v2.0.0) has relied on guzzle6. if php version <=5.3, please use [v1.3](https://github.com/tencentyun/cos-php-sdk-v5/tree/1.3)
