### ISSUE TITLE
request.options参数配置

### ISSUE THREAD

**Issue by xiatian** [tencentyun/cos-php-sdk-v5#56]
Qcloud\Cos\Client::__construct()里面request.options应该把proxy参数默认也带进去，不然这配置代理的话很麻烦。

**Comment by ding-love-yu** [comment]
下载的是release版 cos-php-sdk-v5-1.1.4
报错：

> Qcloud\Cos\Exception\ServiceResponseException: Cos Error Code: InvalidAccessKeyId, Status Code: 403, Cos Request ID: NWFkZWIwY2VfMjRiMjU4NjRfNmYzZV83N2JkNw==, Cos Error Type: client, Cos Error Message: The Access Key Id you provided does not exist in our records

代码截图：
![image](https://user-images.githubusercontent.com/16078611/39166392-eea2748a-47bb-11e8-800c-ea52d1cd6738.png)

求助！第一次使用相信腾讯的实力！不应该这样！

**Comment by lewzylu** [comment]
Phpsdk currently does not support proxy functions, and subsequent scheduled development
