### ISSUE TITLE
release版 cos-php-sdk-v5-1.1.4 测试报错！

### ISSUE THREAD

**Issue by ding-love-yu** [tencentyun/cos-php-sdk-v5#57]
下载的是最新release版 release v1.1.4 
cos-php-sdk-v5-1.1.4
报错：

> Qcloud\Cos\Exception\ServiceResponseException: Cos Error Code: InvalidAccessKeyId, Status Code: 403, Cos Request ID: NWFkZWIwY2VfMjRiMjU4NjRfNmYzZV83N2JkNw==, Cos Error Type: client, Cos Error Message: The Access Key Id you provided does not exist in our records

代码截图：
![image](https://user-images.githubusercontent.com/16078611/39166392-eea2748a-47bb-11e8-800c-ea52d1cd6738.png)

求助！第一次使用相信腾讯的实力！不应该这样！ps:我用的COS是官方提供的免费体验COS API秘钥也配置过配置如图！马上需要使用COS预先测试下！

**Comment by lewzylu** [comment]
请问具体是使用哪个接口

**Comment by ding-love-yu** [comment]
使用的就是示例文件sample.php 中的接口 任何一个接口都会报这个错误，我重新下载了上一个release版本的SDK是可用的，推测最新的release有问题，望修复！

**Comment by ding-love-yu** [comment]
现在测试正确了！

**Comment by lewzylu** [comment]
好奇怪。到底行不行的

**Comment by lewzylu** [comment]
是不是因为是刚申请的secretid 还没生效
