### ISSUE TITLE
更新到1.2.0 版本，提示 class Qcloud\Cos\Client not found

### ISSUE THREAD

**Issue by tanzhenxing** [tencentyun/cos-php-sdk-v5#60]
更新到1.2.0 版本，提示 class Qcloud\Cos\Client not found

![image](https://user-images.githubusercontent.com/11799226/39283608-9bad4854-4941-11e8-9586-795ee5e45b19.png)

是不是  因为删除了依赖的两个包？
![image](https://user-images.githubusercontent.com/11799226/39283686-fb8e01a0-4941-11e8-85c0-ee468a39b6af.png)

我退回到 1.1.4 版，就正常了

**Comment by freyo** [comment]
目前只有先回退一下
`composer require qcloud/cos-sdk-v5:1.1.*`
