### ISSUE TITLE
your policy or acl has reached the limit

### ISSUE THREAD

**Issue by arunaetikala** [tencentyun/cos-php-sdk-v5#69]
Hi Team,

I am using this plugin from last 1 month. Everything was fine ( uploading images ). But from yesterday onwards I am getting this issue " **your policy or acl has reached the limit** " in  Qcloud\Cos\Exception\ServiceResponseException. 

Due to this I am unable upload any images to cloud..

Can you please help me out

Thanks in advance!!!!

**Comment by lewzylu** [comment]
Please don't add 'ACL' header when you upload files.Because ACL has a limit
