### ISSUE TITLE
设置region之后，程序里面获取不到region值。

### ISSUE THREAD

**Issue by liminjun** [tencentyun/cos-php-sdk-v5#70]
代码如下：
![image](https://user-images.githubusercontent.com/966009/41140932-ac39f3b8-6b22-11e8-8fdb-7783f5f47d57.png)

调用程序之后，请求的地址是：[http://sytushu-1255313017.cos..myqcloud.com/5b1a128e2b041.jpg](http://sytushu-1255313017.cos..myqcloud.com/5b1a128e2b041.jpg)，`cos`和`myqcloud`之间有2个点号，获取不到设置的region信息。配置的是：sh。

修改`Client.php`中的代码才可以。
![image](https://user-images.githubusercontent.com/966009/41141018-044d8eac-6b23-11e8-8863-9135b45ccec6.png)

**Comment by krwu** [comment]
v5的sdk是xml api，所以region应该是 'ap-shanghai' 吧？
