### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by haroldcyi** [tencentyun/cos-php-sdk-v5#71]
Package operations: 2 installs, 0 updates, 0 removals
  - Installing guzzle/guzzle (v3.8.1): Downloading (100%)         
  - Installing qcloud/cos-sdk-v5 (v1.2.3): Downloading (100%)         
**Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.**
Writing lock file
Generating optimized autoload files

**Comment by Vtrois** [comment]
#54

**Comment by xiatian** [comment]
请官方更新为guzzlehttp/guzzle。

**Comment by andares** [comment]
这都几百年前的了。。官方还没改掉？

**Comment by HFLeon** [comment]
项目下并存这俩库，建议官方升级到最新，支持特性更多，也更安全
guzzlehttp/guzzle (v6.3.3)
guzzle/guzzle (v3.9.3)

**Comment by andares** [comment]
我发工单了，客服说是大约这个巨量的改动需要到今年7月才可能完成。

**Comment by HFLeon** [comment]
我通过guzzlehtt6 封装了一个API，还不错，就用一个上传文件咋这么费劲呢

**Comment by liugehao** [comment]
真的假的

**Comment by shiny** [comment]
我去，现在都2019年5月23了，这个 issue 还没解决。

**Comment by lewzylu** [comment]
[v2.0](Https://github.com/tencentyun/cos-php-sdk-v5/releases/tag/v2.0.0) has relied on guzzle6. if php version <=5.3, please use [v1.3](https://github.com/tencentyun/cos-php-sdk-v5/tree/1.3)
